### ISSUE TITLE
Notebook not working.

### ISSUE THREAD

**Issue by genvara** [tallero/GNUColab#1]
This notebook does not work, at least for me, i haven't touched any of the settings, so it's the default preset.
When starting the notebook, it will create a user and mount gdrive, however when it reaches the Connection section of the notebook, it will crash on the Connect cell, with this error
![image](https://user-images.githubusercontent.com/29339860/95589587-dc950000-0a3c-11eb-92d5-60bafd99c787.png)
When setting "new" in the "If this is your first setup, select new:" option, it will crash with this error:
![image](https://user-images.githubusercontent.com/29339860/95589848-3c8ba680-0a3d-11eb-924b-294bba95cdfe.png)

**Comment by tallero** [comment]
The `new_pair` function needs a string `user` argument, instead there a boolean value (`root`) has been passed to it, fixed in the latest revision.

Keep in mind default settings want you to open an ssh tunnel from the notebook to the machine you are using, so you need to make your machine (or one you can connect to) to be reachable from the outside.

If you can't or don't want to open an ssh connection from the Notebook to a machine of yours and connect just from tor, deselect the `reverse` option in the *Run* section of the *Connection* chapter.

PS: this new revision lets you run *steam*.

**Comment by matheus176** [comment]
same error for me and i´m using the latest version
