### ISSUE TITLE
some more issues

### ISSUE THREAD

**Issue by genvara** [tallero/GNUColab#2]
Again, this notebook is running at default settings.

Running the "Simple Keep Alive" cell at the "Persistence" section of the notebook would keep running and won't execute successfully, will keep spamming "Error: Can't open display: (null) Failed creating new xdo instance" (had to manually interrupt to stop it)
![image](https://user-images.githubusercontent.com/29339860/95651857-f0943c80-0ae4-11eb-97ec-9de056b48b8a.png)
The "Restore" cell looks like it runs successfully, but it doesn't? it outputs "No such file or directory" so i don't think it's running correctly? maybe im wrong. 
![image](https://user-images.githubusercontent.com/29339860/95651898-39e48c00-0ae5-11eb-8315-902ff4d61cd2.png)
Oh, and this just doesn't work lol
![image](https://user-images.githubusercontent.com/29339860/95651945-7ca66400-0ae5-11eb-9429-ff4f3d7f185f.png)
This also doesn't work
![image](https://user-images.githubusercontent.com/29339860/95652034-25ed5a00-0ae6-11eb-8d20-1c53028e96dc.png)
The "Connect" cell also doesn't work, reverse proxy is disabled.
![image](https://user-images.githubusercontent.com/29339860/95652159-0efb3780-0ae7-11eb-8f63-f8025329e596.png)
Here is the "Connect" cell config:
![image](https://user-images.githubusercontent.com/29339860/95652179-381bc800-0ae7-11eb-970b-47d51cd5970d.png)

And here's some suggestions:
- I recommend trying to implement pyngrok as a way to connect to the notebook (https://github.com/alexdlaird/pyngrok)
- I also recommend removing the ethminer cell from this notebook, it could get you banned, putting your wallet address is enough.

**Comment by tallero** [comment]
>Running the "Simple Keep Alive" cell at the "Persistence" section of the notebook would keep running and won't execute successfully, will keep spamming "Error: Can't open display: (null) Failed creating new xdo instance" (had to manually interrupt to stop it)

*Press this button from the desktop environment to keep this machine alive for 12 hours.*

It means inside VNC session. I will split persistence in `load`/`save` + `no suspend`. I don't like the fact that the to keep the machine turned on we have to run a graphical session, maybe at some point we will have a better alternative.

**Comment by tallero** [comment]
@genvara Apart from the one in the *Connect* cell, all those errors were non-blocking, I should have fixed them completely in the last commit.

>I recommend trying to implement pyngrok as a way to connect to the notebook (https://github.com/alexdlaird/pyngrok)

I did not implement ngrok partly because it is closed-source, but mostly because reverse ssh was the fastest option for a VNC session; I thought that if people just needed a simple universal way to connect they could use Tor anyway (just for connection, inside the session one can run whatever he wants (anydesk, chrome remote desktop, etc.).

I know there is code for ngrok integration in [avatarify](https://github.com/alievk/avatarify), we could look there if the licenses are compatible.
